### ISSUE TITLE
Idea: Let Client post it's username on registration via POST body and encoded

### ISSUE THREAD

**Issue by iCultureBud** [noobcollective/cwf#10]
For now the endpoint for registration on server is called with `/register/{username...}`.

First: {username...} would parse all the trailing segments in the url. We should change it to `{username}`

Second: I think it would be better to let the client send a `POST` with the username encoded in it's body. With such an approach we take away the low hanging fruit for dump brute-force bots to randomly call the endpoint with different random usernames.

**Comment by DrinoSan** [comment]
Thought same but you can also bruteforce the endpoint with a body.

The "..." was a copy pase thing

**Comment by DrinoSan** [comment]
We could just reject requests to register if username is already registered. We just return in the wrapper
